Public Module GameState
    Public Const ConfirmQuit = "ConfirmQuit"
    Public Const Options = "Options"
    Public Const WindowSize = "WindowSize"
    Public Const Volume = "Volume"
    Public Const About = "About"
    Public Const Embark = "Embark"
    Public Const Load = "Load"
    Public Const Neutral = "Neutral"
    Public Const GameMenu = "GameMenu"
    Public Const Save = "Save"
    Public Const Abandon = "Abandon"
    Public Const ActionMenu = "ActionMenu"
    Public Const Inventory = "Inventory"
    Public Const Dead = "Dead"
    Public Const Message = "Message"
    Public Const Navigation = "Navigation"
    Public Const PickUpItem = "PickUpItem"
    Public Const InventoryDetail = "InventoryDetail"
    Public Const Fight = "Fight"
    Public Const Run = "Run"
    Public Const Attack = "Attack"
End Module
