Public Module GameState
    Public Const Neutral = "Neutral"
    Public Const GameMenu = "GameMenu"
    Public Const Save = "Save"
    Public Const Abandon = "Abandon"
    Public Const ActionMenu = "ActionMenu"
    Public Const Inventory = "Inventory"
    Public Const Dead = "Dead"
    Public Const Message = "Message"
    Public Const Navigation = "Navigation"
    Public Const PickUpItem = "PickUpItem"
    Public Const InventoryDetail = "InventoryDetail"
    Public Const Fight = "Fight"
    Public Const Run = "Run"
    Public Const Attack = "Attack"
End Module
